version: '2'
services:
  traefik:
    image: "traefik:v2.4"
    command:
      - "--api.insecure=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"


  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - "./.data/postgres:/var/lib/postgresql/data:rw"

  supertokens:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    environment:
      POSTGRESQL_CONNECTION_URI: "postgresql://admin:admin@db:5432/"

  auth:
    build:
      context: "./services/authentication-server"
    environment:
      SUPERTOKENS_URL: "http://supertokens:3567"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"

  target:
    image: "traefik/whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.target.rule=Host(`localhost`)"
      - "traefik.http.routers.target.entrypoints=web"
      - "traefik.http.routers.target.middlewares=auth"

      - "traefik.http.middlewares.auth.forwardauth.address=http://auth/sessioninfo"
